config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#index'

  resources :posts do
    resources :comments
  end

  resources :profiles

  devise_for :users, controllers: { registrations: 'users/registrations' }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post

  validates :name, :email, :body, presence: true
  # validate :post_should_be_published

  after_create :email_post_author

  # def post_should_be_published
  #   errors.add(:post_id, 'is not published yet') if post && !post.published?
  # end

  def email_post_author
    puts "We will notify #{post.user.email} in Chapter 12" if post.user
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments

  validates :title, :body, :user, presence: true

  scope :downroad, -> { order('created_at DESC') }
  scope :uproad, -> { order('created_at ASC') }
  scope :user, ->(id) { where(['user_id = ?', id]) }

  def published?
    published_at.present?
  end

  def owned_by?(owner)
    return false unless owner.is_a?(User)

    user == owner
  end
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  before_save do
    self.email = email.downcase
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :validatable

  has_many :posts, dependent: :destroy
  has_one :profile
  has_many :replies, through: :posts, source: :comments

  validates :name, presence: true, length: { maximum: 50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |u|
      u.permit(:name, :surname, :email, :password)
    end

    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :surname, :email, :password, :current_password)
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :load_post, only: %i[destroy new create]
  before_action :authenticate_user!, only: %i[create destroy]

  def new; end

  def create
    @comment = @post.comments.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to post_url(@post), notice: 'Obrigado por seu comentário' }
      else
        format.html { redirect_to post_url(@post), alert: 'errou mizeravi' }
      end
    end
  end

  def destroy
    @post = current_user.posts.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to post_url(@post), notice: 'Comentário apagado' }
    end
  end

  private

  def load_post
    @post = Post.find(params[:post_id])
  end

  def comment_params
    user = current_user
    params.require(:comment).permit(:body).merge({ name: user.name, email: user.email })
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[show edit update destroy]
  before_action :authenticate_user!, only: %i[create update edit new destroy]

  # GET /posts or /posts.json
  def index
    current_page = (params[:page] || 0).to_i

    @posts = Post
             .downroad
             .page(current_page).per 4
  end

  # GET /posts/1
  def show; end

  # GET /posts/new
  def new
    @post = current_user.posts.build
  end

  # GET /posts/1/edit
  def edit; end

  # POST /posts
  def create
    @post = current_user.posts.build post_params

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: 'Nova estória criada.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: 'Estória corrigida.' }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Estória agora esquecida.' }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    # current post as anonimous reader
    @post = Post.find params[:id]

    # user is signed in? and is it the current post author?
    @post = current_user.posts.find(params[:id]) if helpers.has_all_permissions?
  end

  # Only allow a list of trusted parameters through.
  def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: %i[show edit update]
  before_action :set_posts, only: %i[show]
  before_action :set_permission, only: %i[show]

  def show; end

  def edit; end

  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html do
          redirect_to profile_url(@profile), notice: 'Perfil atualizado com sucesso.'
        end
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  private

  def set_posts
    p = Profile.find params[:id]
    @posts = @profile.user.posts.user(p.user_id)
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_profile
    @profile = Profile.find params[:id]
  end

  def set_permission
    # user found and is the correct user to edit current profile.
    @all_permissions = user_signed_in? && current_user.profile.id == @profile.id
  end

  # Only allow a list of trusted parameters through.
  def profile_params
    params.require(:profile).permit(:bio)
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
  after_action :create_profile, only: %(create)

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    super
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # create a new profile to the just registered user.
  def create_profile
    current_user.create_profile! name: current_user.name,
                                 bio: 'Sem informações.'
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :set_posts

  def index; end

  private

  def set_posts
    current_page = (params[:page] || 0).to_i
    @posts = Post.order(created_at: :desc)
                 .page(current_page).per 3
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def has_all_permissions?
    user_signed_in? && current_user.id == @post.user_id
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/_comment.html.erb
<p class="col">
  <b><%= comment.name %></b>: <%= strip_tags comment.body %>
  <% if @post.owned_by? current_user %>
    <%= link_to 'apagar', post_comment_path(post_id: @post, id: comment),
          confirm: 'Are you sure?', method: :delete, class: 'small text-muted col' %>
  <% end %>
</p>

app/views/comments/_new.html.erb
<%= form_with(model: @post.comments.new, url: post_comments_path(@post), local: true) do |form| %>
  <div class="form-group">
    <%= form.text_area :body, placeholder: 'Deixe seu comentario', class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit 'Enviar', class: 'btn btn-primary my-2' %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Babu</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
      <%= render "shared/navbar" %>
      <%= render "shared/notices" %>

    <div id="main-site" class="container">
      <%= yield %>
    </div>

    <%= render "shared/footer" %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="card mb-2 mt-2">
    <div class="card-body">
      <h2 class="card-title"><%= main_title %></h2>
      <div class="form-group mb-2">
        <%= form.text_field :title, placeholder: "titulo",  class: "form-control" %>
      </div>

      <div class="form-group">
        <%= form.text_area :body, placeholder: "estoria", class: 'form-control' %>
      </div>

      <div class="actions">
        <%= form.submit 'Enviar', class: "btn btn-warning btn-block mt-2" %>
      </div>
    </div>
  </div>
<% end %>

app/views/posts/edit.html.erb
<%= link_to 'Voltar', posts_path, class: "btn btn-primary mb-2" %>

<%= render partial: 'form', locals: { post: @post, main_title: 'Editando a estória' } %>

app/views/posts/index.html.erb
<%= link_to 'Nova estória', new_post_path, class: 'btn btn-primary' %>

<section class="mt-4">
  <% @posts.each do |post| %>
    <%= link_to(post, class: 'list-group-item list-group-item-action d-flex gap-3 py-3') do %>
      <img src="https://cdn4.iconfinder.com/data/icons/gadgets-3/130/_Lego-512.png" alt="twbs" class="rounded-circle flex-shrink-0" width="32" height="32">
      <div class="d-flex gap-2 w-100 justify-content-between">
        <div>
          <h6 class="mb-0"><%= post.title %></h6>
          <p class="mb-0 opacity-75"><%= strip_tags post.body.truncate 80 %></p>
        </div>
        <small class="opacity-50 text-nowrap"><%= post.user.name %></small>
      </div>
    <% end %>
  <% end %>
</section>

<section class="mt-3">
  <%= link_to_next_page @posts, 'antigas', class: 'btn btn-outline-primary' %>
  <%= link_to_previous_page @posts, 'novas', class: 'btn btn-outline-secondary' %>
</section>

app/views/posts/new.html.erb
<%= link_to 'Voltar', posts_path, class: "btn btn-primary mb-2" %>

<%= render partial: 'form', locals: { post: @post, main_title: 'Nova estória' } %>

app/views/posts/show.html.erb
<%= link_to 'Voltar', posts_path, class: "btn btn-outline-primary" %>

<div class="card mb-2 mt-2">
  <div class="card-body">
    <h2 class="card-title"><%= @post.title %></h2>
    <small class="opacity-70 text-nowrap"><%= link_to @post.user.name, profile_path(id: @post.user.profile.id), class: "" %> |
      <%= @post.created_at.to_date %></small>
    <p><%= strip_tags @post.body %></p>
  </div>
</div>

<% if has_all_permissions? %>
  <%= link_to 'Editar', edit_post_path(@post), class: "btn btn-outline-success" %>
  <%= link_to 'Deletar', @post, method: :delete, class: "btn btn-outline-danger", data: { confirm: 'Tem certeza?' } %>
<% end %>

<section class="mt-2">
  <h3>Comentários</h3>
  <% if @post.comments.any? %>
    <%= render @post.comments %>
  <% end %>

  <%= render 'comments/new' %>
</section>

app/views/profiles/_form.html.erb
<%= form_with(model: profile) do |form| %>
  <% if profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
        <% profile.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="card mb-2 mt-2">
    <div class="card-body">
      <h2 class="card-title"><%= main_title %></h2>
      <div class="form-group">
        <%= form.text_field :bio, placeholder: "bio",  class: "form-control" %>
      </div>

      <div class="actions">
        <%= form.submit 'Pronto', class: "btn btn-warning btn-block mt-2" %>
      </div>
    </div>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<%= link_to 'Voltar', posts_path, class: "btn btn-primary mb-2" %>

<%= render partial: 'form', locals: { profile: @profile, main_title: 'Editando bio' } %>

app/views/profiles/show.html.erb
<div class="row">
  <section class="col-sm">
    <h3><%= @profile.name.capitalize %></h3>
    <p><%= @profile.bio %></p>

    <% if @all_permissions %>
      <%= link_to 'Editar Bio', edit_profile_path, class: "btn btn-primary" %>
    <% end %>
  </section>

  <section class="col-sm" id="my-stories">
    <h3>Suas estórias (<%= @profile.user.posts.count %>)</h3>
    <ul>
      <% @posts.each do |post| %>
        <li>
          <%= link_to post.title, post, class: 'link-dark' %>
          <small class="grey"><%= post.created_at.to_date %></small>
        </li>
      <% end  %>
    </ul>
  </section>
</div>

app/views/shared/_navbar.html.erb
<header class="py-3">
    <div class="mx-4 d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
        <%= link_to "Babu", root_path, id: "logo", class: 'navbar-brand bi me-2 pb-2' %>

        <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
            <li><%= link_to 'Estórias', posts_path, class: "nav-link px-2" %></li>
            <li><%= link_to 'Ler código-fonte', 'https://github.com/easbarba/babu', class: 'nav-link px-2' %></li>
        </ul>

        <div class="mx-2">
            <% if user_signed_in? %>
                <%= link_to current_user.name.capitalize, profile_path(current_user.profile.id), class: "btn btn-outline-dark" %>
                <%= link_to 'Sair', destroy_user_session_path, method: :delete, class: "btn btn-outline-danger" %>
            <% else %>
                <%= link_to 'Entrar', new_user_session_path, class: "btn btn-outline-primary me-2" %>
                <%= link_to 'Registar', new_user_registration_path, class: "btn btn-success btn-registration" %>
            <% end %>
        </div>

        <form class="col-12 col-lg-auto" role="search">
            <input type="search" class="form-control" placeholder="Procurar..." aria-label="Search">
        </form>
    </div>
</header>

app/views/shared/_notices.html.erb
<% if notice.present? %>
<aside class="alert alert-info">
    <%= notice %>
</aside>
<% end %>
<% if alert.present? %>
<aside class="alert alert-danger">
    <%= alert %>
</aside>
<% end %>

app/views/welcome/index.html.erb
<section class="jumbotron">
  <h1 class="display-4"><% t('.title') %></h1>
  <p class="lead">Nunc pharetra sapien in eros iaculis.</p>
  <hr class="my-4">
  <p>Morbi eu justo leo. Etiam pharetra vulputate mi eget consectetur. Nunc
    pharetra sapien in eros iaculis, nec laoreet turpis luctus. Sed pharetra lacus
    ac ligula convallis accumsan.</p>
</section>

<section class="m-1 row" id="welcome-posts">
  <% @posts.each do |post| %>
    <div class="col-sm card m-1">
      <%= link_to post, class: "card-body" do %>
        <h5 class="card-title"><%= post.title %></h5>
        <p><%= strip_tags post.body.truncate 100 %></p>
      <% end  %>
    </div>
  <% end  %>
</section>

<%= link_to 'Read more stories', posts_path, class: 'btn btn-outline-dark m-1' %>